name: CI

on: pull_request

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.194.0
        with:
          bundler-cache: true
      - name: Run tests
        env:
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120
          ENCODED_SECRETS_PLIST: ${{ secrets.ENCODED_SECRETS_PLIST }}
          ENCODED_GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.ENCODED_GOOGLE_SERVICE_INFO_PLIST }}
        run: make ci-test
