name: Deploy Beta

on:
  push:
    branches: main

jobs:
  beta:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.194.0
        with:
          bundler-cache: true
      - uses: actions/setup-python@v5
      - name: Setup build dependencies
        run: make py-deps
      - name: Bump beta version
        run: bumpver update --no-commit
      - name: Deploy Beta to Test Flight
        env:
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120
          ENCODED_SECRETS_PLIST: ${{ secrets.ENCODED_SECRETS_PLIST }}
          ENCODED_GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.ENCODED_GOOGLE_SERVICE_INFO_PLIST }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          ENCODED_APP_STORE_CONNECT_API_KEY: ${{ secrets.ENCODED_APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_APPLE_ID: ${{ secrets.APP_STORE_CONNECT_APPLE_ID }}
          MATCHFILE_GIT_URL: ${{ secrets.MATCHFILE_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
        run: make deploy-beta
